[2024-11-24T05:15:01.005+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.load_to_mysql manual__2024-11-24T05:14:56.405263+00:00 [queued]>
[2024-11-24T05:15:01.012+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.load_to_mysql manual__2024-11-24T05:14:56.405263+00:00 [queued]>
[2024-11-24T05:15:01.013+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-11-24T05:15:01.023+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): load_to_mysql> on 2024-11-24 05:14:56.405263+00:00
[2024-11-24T05:15:01.029+0000] {standard_task_runner.py:57} INFO - Started process 176 to run task
[2024-11-24T05:15:01.031+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'load_to_mysql', 'manual__2024-11-24T05:14:56.405263+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmp_ovf9l3j']
[2024-11-24T05:15:01.034+0000] {standard_task_runner.py:85} INFO - Job 21: Subtask load_to_mysql
[2024-11-24T05:15:01.074+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_reddit_pipeline.load_to_mysql manual__2024-11-24T05:14:56.405263+00:00 [running]> on host ed5257f0374c
[2024-11-24T05:15:01.136+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yusuf Ganiyu' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='load_to_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-11-24T05:14:56.405263+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-24T05:14:56.405263+00:00'
[2024-11-24T05:15:01.180+0000] {logging_mixin.py:151} INFO - Connected to MySQL database
[2024-11-24T05:15:01.223+0000] {logging_mixin.py:151} INFO - Table 'reddit_data' checked/created successfully
[2024-11-24T05:15:01.228+0000] {logging_mixin.py:151} INFO - Error uploading data to MySQL: 1366 (HY000): Incorrect integer value: 'False' for column 'over_18' at row 1
[2024-11-24T05:15:01.228+0000] {logging_mixin.py:151} INFO - MySQL connection closed
[2024-11-24T05:15:01.228+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-11-24T05:15:01.235+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=etl_reddit_pipeline, task_id=load_to_mysql, execution_date=20241124T051456, start_date=20241124T051501, end_date=20241124T051501
[2024-11-24T05:15:01.284+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-11-24T05:15:01.296+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
